apiVersion: v1
kind: Pod
metadata:
  name: enb-waw
spec:
  hostname: enb-waw
#  hostNetwork: true
  containers:
  - image: index.docker.io/rychukarter/oai_enb:1.0.0
    name: oai-enb-waw
    securityContext:
      privileged: true
#      capabilities:
#        add: ["ALL"]
    command: ["sleep", "9000"]
    env:
    - name: MME_HOST
      value: mme-waw
    - name: IFACE_S1
      value: eth0
    - name: IFACE_S1U
      value: eth0
    - name: PORT_S1U 
      value: "2152"
    - name: ID_ENB
      value: "0xe00"
    - name: TAC
      value: "1"
    - name: MCC
      value: "208"
    - name: MNC
      value: "93"
    volumeMounts:
    - name: kernel-modules
      mountPath: /lib/modules
    - name: usb-bus
      mountPath: /dev/bus/usb
  volumes:
  - name: kernel-modules
    hostPath:
      path: /lib/modules
      type: Directory
  - name: usb-bus
    hostPath:
      path: /dev/bus/usb
      type: Directory
