apiVersion: v1
kind: Service
metadata:
  name: mme-waw
spec:
  ports:
  - port: 3870
    name: fd-primary
  - port: 5870
    name: fd-secondary
  - port: 36412
    name: s1ap
  - port: 2123
    name: s11
  selector:
    app: mme-waw
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mme-waw
spec:
  selector:
    matchLabels:
      app: mme-waw
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mme-waw
    spec:
      containers:
      - image: index.docker.io/rychukarter/oai_mme:3.0.1
        name: oai-mme-waw
#       command: ["sleep", "9000"]
        env:
        - name: MME_HOST
          value: mme-waw
        - name: MME_REALM
          value: openair4G.eur
        - name: HSS_HOST
          value: hss-waw
        - name: HSS_REALM
          value: openair4G.eur
        - name: SPGW_HOST
          value: spgw-waw
        - name: IFACE_S1
          value: eth0
        - name: IFACE_S11
          value: eth0
        ports:
        - containerPort: 3870
          name: fd-primary
        - containerPort: 5870
          name: fd-secondary
        - containerPort: 36412
          name: s1ap
        - containerPort: 2123
          name: s11
