apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: oai-db
        - name: MYSQL_USER
          value: oai-db
        - name: MYSQL_DATABASE
          value: oai_db
        - name: MYSQL_PASSWORD
          value: oai-db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: init-dir
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: init-dir
        hostPath:
          path: /k8s/mysql/docker-entrypoint-initdb.d
          type: Directory
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

